### ISSUE TITLE
Can you add the safe-blocks option

### ISSUE THREAD

**Issue by haha44444** [DeathGOD7/unexpectedspawn-paper#10]
Maybe you can add the option to turn on or off blacklists and whitelists, because I don't like use blacklists.

**Comment by RexSE7EN** [comment]
Did you mean blacklist worlds or blacklist blocks?
If you wanna disable it, just leave it blank. (eg : [])

**Comment by haha44444** [comment]
> 你是说黑名单世界还是黑名单块？
> 如果您想禁用它，只需将其留空。（例如：[]）

emm... I hope you can add a whitelist like this: spawn-block-whitelist
(Sorry, I have to go to bed now.)

**Comment by RexSE7EN** [comment]
> > 你是说黑名单世界还是黑名单块？
> > 如果您想禁用它，只需将其留空。（例如：[]）
> 
> emm... I hope you can add a whitelist like this: spawn-block-whitelist

For example: If you want the players to spawn in obsidian or lava, you can just remove that in the black list of spawn blocks.
If the random location block is that 2 (obsidian or lava), it will tp users to that.
(Summary: Anything that is not in spawn blacklist block is whitelisted where the player can spawn.)

**Comment by haha44444** [comment]
But this may be a bit troublesome for me. I want players to spawn only on some blocks.
like this:
![image](https://user-images.githubusercontent.com/60396495/126909275-c5ae83b8-61db-4ad5-a636-c13bf74f2f9b.png)

**Comment by RexSE7EN** [comment]
> But this may be a bit troublesome for me. I want players to spawn only on some blocks.
> like this:
> ![image](https://user-images.githubusercontent.com/60396495/126909275-c5ae83b8-61db-4ad5-a636-c13bf74f2f9b.png)

Instead of a new config key, I think it's best to add like invert: true/false. Which reverts the config (What I meant was: If you have grass block only on spawn blacklist and enabled invert then it will only use or find the random location which highest block is grass and tp users there.)

Will see in the future and add it to my fork and ask Shivelight for the pull request. (Version 0.3.0 ([from my fork](https://github.com/DeathGOD7/unexpectedspawn-paper)) still isn't released in the main repo or spigot page.)

**Comment by RexSE7EN** [comment]
@haha44444 Please try this beta from my repo. It will be merged in the future if no bugs are found. Also please report back the results. Also if possible please test it from 1.8 - 1.16. Thank you.

[Unexpected Spawn v0.3.1 (Beta Build)](https://github.com/DeathGOD7/unexpectedspawn-paper/releases/tag/0.3.1-beta)

**Comment by RexSE7EN** [comment]
Added in new 0.3.1 version.
