### ISSUE TITLE
End City remote gateway and end portal bug

### ISSUE THREAD

**Issue by DeathGOD7** [DeathGOD7/unexpectedspawn-paper#9]
The Player reported that they respawn in bed even though they break a bed and die (Maybe plugin conflict with multiverse inventory or last location plugin).
And people who die in end city seem to cause an error in console.
And also needs check-in main end island.

**Paper Version** : 1.17/1.17.1 (Probably in 1.17.1)
**Unexpected Spawn Version** : v0.3.0-SNAPSHOT

I will update this issue after I verify it.

&dash; SE7EN

**Comment by RexSE7EN** [comment]
Update 1 : 
~~It happens with multiverse as it seems to save bed location. So if you put the bed, set respawn and break bed then put it back at the same place... it will remember the loc of the bed and use that.~~ Problem of the multiverse or intended feature of the multiverse. Not related to our plugin. 

~~New minor bug: if you die in nether and haven't specified global respawn world in global config but have one for main overworld world then it seems to use the global or nether world as respawn point.~~ FIXED in a v0.3.0 full release

If in old builds and to fix it, you have to do either of these two things:
- specify in a global config or have nether worlds own respawn world.
- or delete the config.yml file and let plugin(v0.3.0) remake the config file.

~~Might add ignore flag if the world is neither.~~
No need to add ignore flag.

**Comment by RexSE7EN** [comment]
Update 2: ~~Player who uses end portal or use end gateway causes error to show up in console that world is not found.~~

~~Might need to dig down on docs of paper.~~ FIXED in v0.3.0 as when returning to overworld from end, player don't actually die but just respawns in bed. Which led to an error when looking for death world and returns null.

**Comment by RexSE7EN** [comment]
All things here are resolved. Please use the latest version from the release tab or from the spigot. Closing this issue.
